[project]
name = 'pizza-square'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.pizza-faktory]
path = 'contracts/pizza-faktory.clar'
clarity_version = 3
epoch = '3.2'

[contracts.pizza-faktory-pool]
path = 'contracts/pizza-faktory-pool.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
